[package]
name = "holi_wasm_renderer"
version = "0.1.0"
edition = "2021"
description = "Holi.tools WebGPU renderer (WASM)"
license = "AGPL-3.0"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-futures = "0.4"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
    "HtmlCanvasElement",
    "Window", 
    "console"
]}
console_error_panic_hook = "0.1"
log = "0.4"

# Graphics
wgpu = { version = "23.0", features = ["webgpu", "webgl"] }
gloo = { version = "0.11", features = ["render"] }
lyon = "1.0"
bytemuck = { version = "1.16", features = ["derive", "min_const_generics"] }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
