[package]
name = "holi-qr-svg"
version = "0.1.0"
edition = "2021"
description = "Micro Rust SVG generator for QR codes (<10KB)"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wee_alloc = "0.4"
# Using qrcodegen-no-std for pure logic size
qrcodegen = { version = "1.8", default-features = false }

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
strip = true

[package.metadata.wasm-pack.profile.release]
wasm-opt = false
